timeout: 3600s
options:
  substitution_option: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',
          '-t', 'gcr.io/$PROJECT_ID/jupyter-test:latest',
          '-f', 'test/Dockerfile',
          'test'
        ]
- name: 'gcr.io/$PROJECT_ID/jupyter-test:latest'
  env:
  - PROJECT_ID=$PROJECT_ID
  - WORKSPACE=/workspace
  - GCS_TRUSTED_MIRROR=$_GCS_TRUSTED_MIRROR
artifacts:
  objects:
    location: ${_ARTIFACT_LOCATION}/${BUILD_ID}
    paths: [
             '/workspace/artifacts/*',
           ]
substitutions:
  _ARTIFACT_LOCATION: 'gs://test-results-anthoscli'
  _GCS_TRUSTED_MIRROR: 'gs://anthoscli-test-cloudbuild-mirror'
